catalog-service:
  welcome-message: "This is the Children Universe Catalog Service. Welcome!"

# spring cloud configs
spring:
  application:
    name: catalog-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
      request-connect-timeout: 5000
      request-read-timeout: 5000
      fail-fast: false
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
  datasource:
    username: petre
    password: admin
    url: jdbc:postgresql://localhost:5432/catalog_service_db
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
  sql:
    init:
        mode: always


# server configs
server:
  address: 0.0.0.0
  port: 9001
  tomcat:
    connection-timeout: 3s
    keep-alive-timeout: 15s
    threads:
      max: 30
      min-spare: 5



# management configs
management:
  endpoints:
    web:
      exposure:
        include: refresh # exposes the /actuator/refresh endpoint